name: Docker image CI

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - '8.1/**'
      - '8.2/**'
      - '8.3/**'
      - '8.4/**'
  schedule:
    - cron: '0 1 * * 6'
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: [ubuntu-24.04]

    strategy:
      fail-fast: false
      matrix:
        version: [8.1-trixie, 8.2-trixie, 8.3-trixie, 8.4-trixie]
        include:
          - version: 8.1-trixie
            docker-context: 8.1/debian/apache/default
            docker-tags: |
              nicoherbigde/typo3-cms-php:8.1-apache
              nicoherbigde/typo3-cms-php:8.1-apache-trixie
              nicoherbigde/typo3-cms-php:8.1.33-apache
              nicoherbigde/typo3-cms-php:8.1.33-apache-trixie
          - version: 8.2-trixie
            docker-context: 8.2/debian/apache/default
            docker-tags: |
              nicoherbigde/typo3-cms-php:8.2-apache
              nicoherbigde/typo3-cms-php:8.2-apache-trixie
              nicoherbigde/typo3-cms-php:8.2.29-apache
              nicoherbigde/typo3-cms-php:8.2.29-apache-trixie
          - version: 8.3-trixie
            docker-context: 8.3/debian/apache/default
            docker-tags: |
              nicoherbigde/typo3-cms-php:8.3-apache
              nicoherbigde/typo3-cms-php:8.3-apache-trixie
              nicoherbigde/typo3-cms-php:8.3.25-apache
              nicoherbigde/typo3-cms-php:8.3.25-apache-trixie
          - version: 8.4-trixie
            docker-context: 8.4/debian/apache/default
            docker-tags: |
              nicoherbigde/typo3-cms-php:8.4-apache
              nicoherbigde/typo3-cms-php:8.4-apache-trixie
              nicoherbigde/typo3-cms-php:8.4.12-apache
              nicoherbigde/typo3-cms-php:8.4.12-apache-trixie

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image and Push it to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.docker-context }}
          no-cache: true
          pull: true
          push: true
          tags: ${{ matrix.docker-tags }}
